### ISSUE TITLE
Invalid YAML format in README

### ISSUE THREAD

**Issue by tyrannosaurusjames** [WPP-Public/akqa-nz-silverstripe-elastica#45]
The YAML format in the README for adding extra indexed_fields to classes that extend the base class is invalid:

```
Your\Namespace\Page:
  extensions:
    - Heyday\Elastica\Searchable
  indexed_fields: &page_defaults
    - Title
    - MenuTitle
    - Content
    - MetaDescription

Your\Namespace\OtherPage: # extends Your\Namespace\Page
  indexed_fields:
    <<: *page_defaults
    - BannerHeading
    - BannerCopy
    - SubHeading
```

This YAML format doesn't appear to be an agreed part of the spec - here is a feature request for a very similar format that was declined: https://github.com/yaml/yaml/issues/35

Attempting to run a `dev/build` using the format documented here will result in an error like this:

```
Fatal error: Uncaught Symfony\Component\Yaml\Exception\ParseException: You cannot define a sequence item when in a mapping at line 68 (near "- BannerHeading"). in /path/vendor/symfony/yaml/Parser.php:146
```

This question on Stack Overflow also appears to indicate it's not really possible: https://stackoverflow.com/questions/4948933/is-there-a-way-to-alias-anchor-an-array-in-yaml

One answer from that question does give a solution that works (https://stackoverflow.com/a/67265299)

An equivalent format that works would be:

```
Your\Namespace\Page:
  extensions:
    - Heyday\Elastica\Searchable
  indexed_fields: &page_defaults
    1: Title
    2: MenuTitle
    3: Content
    4: MetaDescription

Your\Namespace\OtherPage: # extends Your\Namespace\Page
  indexed_fields:
    <<: *page_defaults
    5: BannerHeading
    6: BannerCopy
    7: SubHeading
```

It's a bit of a pain to keep track of the integer keys, but it seems like it is the only way to avoid a lot of copy/paste
